src/Entity/Document.php
<?php

namespace App\Entity;

use App\Repository\DocumentRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: DocumentRepository::class)]
class Document
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $label = null;

    #[ORM\Column(length: 255)]
    private ?string $documentSource = null;

    private ?string $old_document = null;

    #[ORM\ManyToMany(targetEntity: Category::class)]
    private Collection $category;

    public function __construct()
    {
        $this->category = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLabel(): ?string
    {
        return $this->label;
    }

    public function setLabel(string $label): static
    {
        $this->label = $label;

        return $this;
    }

    public function getDocumentSource(): ?string
    {
        return $this->documentSource;
    }

    public function setDocumentSource(string $documentSource): static
    {
        $this->documentSource = $documentSource;

        return $this;
    }

    /**
     * @return Collection<int, Category>
     */
    public function getCategory(): Collection
    {
        return $this->category;
    }

    public function addCategory(Category $category): static
    {
        if (!$this->category->contains($category)) {
            $this->category->add($category);
        }

        return $this;
    }

    public function removeCategory(Category $category): static
    {
        $this->category->removeElement($category);

        return $this;
    }

    /**
     * Get the value of old_document
     *
     * @return ?string
     */
    public function getOldDocument(): ?string
    {
        return $this->old_document;
    }

    /**
     * Set the value of old_document
     *
     * @param ?string $old_document
     *
     * @return self
     */
    public function setOldDocument(?string $old_document): self
    {
        $this->old_document = $old_document;

        return $this;
    }

    public function getCategoryLabels(): array
    {
        $categoryLabels = [];

        foreach ($this->category as $category) {
            $categoryLabels[] = $category->getLabel();
        }

        return $categoryLabels;
    }
}

src/Form/DocumentType.php
<?php

namespace App\Form;

use App\Entity\Document;
use App\Entity\Category;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;

class DocumentType extends AbstractType
{
    private $entityManager;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }


    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $is_creation = $options['is_creation'];
        $chooseCategory = $options['chooseCategory'];

        $builder
            ->add('label')
            ->add('documentSource', FileType::class, [
                'data_class' => null,
                'required' => $is_creation,
                'empty_data' => $is_creation ? true : false,
                'constraints' => $is_creation ? [
                    new File([
                        'mimeTypes' => ['application/pdf'],
                        'mimeTypesMessage' => 'Veuillez télécharger un fichier PDF valide.',
                    ]),
                ] : [],
            ])
            ->add('old_document', HiddenType::class);
        if ($chooseCategory){
            $builder
                ->add('category', EntityType::class, [
                    'class' => Category::class,
                    'choice_label' => 'label',
                    'multiple' => true,
                    'expanded' => true,
                    'by_reference' => false,
                    'query_builder' => function (EntityRepository $er) {
                        return $er->createQueryBuilder('c')
                            ->andWhere('c.label IN (:label)')
                            ->setParameter('label', [
                                'périscolaire', 
                                'mercredi', 
                                'loisirs'
                            ]);
                    },
                ])
            ;
        }else{
            $associationCategory = $this->entityManager->getRepository(Category::class)->findOneBy(['label' => 'association']);
            $builder
                ->add('category', EntityType::class, [
                    'class' => Category::class,
                    'choice_label' => 'label',
                    'multiple' => true,
                    'expanded' => true,
                    'by_reference' => false,
                    'query_builder' => function (EntityRepository $er) {
                        return $er->createQueryBuilder('c')
                            ->andWhere('c.label IN (:label)')
                            ->setParameter('label', [
                                'association',
                            ]);
                    },
                    'data' => [$associationCategory],
                    'attr' => [
                        'class' => 'd-none',
                    ]
                ])
            ;
        }
            
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Document::class,
            'is_creation' => false,
            'chooseCategory' => false
        ]);
    }
}

src/Controller/DocumentController.php
<?php

namespace App\Controller;

use App\Entity\Document;
use App\Form\DocumentType;
use App\Repository\CategoryRepository;
use App\Repository\DocumentRepository;
use App\Service\CategoryService;
use App\Service\FileUploaderService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/document')]
class DocumentController extends AbstractController
{
    #[Route('/{category_label}/liste', name: 'app_document_index', methods: ['GET'])]
    public function index(
        DocumentRepository $documentRepository, 
        $category_label,
        CategoryService $categoryService,
    ): Response
    {
        if (!$categoryService->categoryDocumentExists($category_label)) {
            throw $this->createNotFoundException('Page introuvable');
        }
        if($category_label == "infos"){
            return $this->render('document/index.html.twig', [
                'documents' => $documentRepository->findAllWithoutAssociation(),
                'category_label' => $category_label,
            ]);
        }else{
            return $this->render('document/index.html.twig', [
                'documents' => $documentRepository->findByCategoryLabel($category_label),
                'category_label' => $category_label,
            ]);
        }
    }

    #[Route('/{category_label}/new', name: 'app_document_new', methods: ['GET', 'POST'])]
    public function new(
        Request $request, 
        EntityManagerInterface $entityManager, 
        FileUploaderService $fileUploaderService,
        $category_label,
        CategoryService $categoryService,
    ): Response
    {
        if (!$categoryService->categoryDocumentExists($category_label)) {
            throw $this->createNotFoundException('Page introuvable');
        }
        $chooseCategory = $category_label == "association" ? false : true;
        $document = new Document();
        $form = $this->createForm(DocumentType::class, $document, ['is_creation' => true, 'chooseCategory' => $chooseCategory]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if ($documentSource = $form['documentSource']->getData()) {
                $label = $form['label']->getData();
                $filename = $fileUploaderService->uploadDocument($documentSource, $label);
                $document->setDocumentSource($filename);
            }
            $entityManager->persist($document);
            $entityManager->flush();

            return $this->redirectToRoute('app_document_index', ['category_label' => $category_label], Response::HTTP_SEE_OTHER);
        }

        return $this->render('document/new.html.twig', [
            'document' => $document,
            'form' => $form,
            'category_label' => $category_label
        ]);
    }

    #[Route('/{id}', name: 'app_document_show', methods: ['GET'])]
    public function show(Document $document): Response
    {
        return $this->render('document/show.html.twig', [
            'document' => $document,
        ]);
    }

    #[Route('/{category_label}/edit/{id}', name: 'app_document_edit', methods: ['GET', 'POST'])]
    public function edit(
        Request $request, 
        Document $document, 
        EntityManagerInterface $entityManager, 
        FileUploaderService $fileUploaderService,
        $category_label,
        CategoryService $categoryService,
    ): Response
    {
        if (!$categoryService->categoryDocumentExists($category_label)) {
            throw $this->createNotFoundException('Page introuvable');
        }
        if (!$document->getOldDocument() && $document->getDocumentSource()) {
            $document->setOldDocument($document->getDocumentSource());
        }

        $chooseCategory = $category_label == "association" ? false : true;

        $form = $this->createForm(DocumentType::class, $document, ['chooseCategory' => $chooseCategory]);
        $form->handleRequest($request);


        
        if ($form->isSubmitted() && $form->isValid()) {

            // si un nouveau document est chargé
            if ($documentSource = $form['documentSource']->getData()) {
                $label = $form['label']->getData();
                $filename = $fileUploaderService->uploadDocument($documentSource, $label);
                $document->setDocumentSource($filename);
                if ($old_document = $form['old_document']->getData()){
                    $docPath = $this->getParameter("document_dir").$old_document;
                    // on supprime du dossier
                    if(file_exists($docPath)){
                        unlink($docPath);
                    }
                }
            }else{
                $document->setDocumentSource($document->getOldDocument());
            }
            
            $entityManager->flush();

            return $this->redirectToRoute('app_document_index', ['category_label' => $category_label], Response::HTTP_SEE_OTHER);
        }

        return $this->render('document/edit.html.twig', [
            'document' => $document,
            'form' => $form,
            'category_label' => $category_label,
        ]);
    }

    #[Route('/{category_label}/delete/{id}', name: 'app_document_delete', methods: ['POST'])]
    public function delete(
        Request $request, 
        Document $document, 
        EntityManagerInterface $entityManager,
        $category_label,
        CategoryService $categoryService,
    ): Response
    {
        if (!$categoryService->categoryDocumentExists($category_label)) {
            throw $this->createNotFoundException('Page introuvable');
        }
        if ($this->isCsrfTokenValid('delete'.$document->getId(), $request->request->get('_token'))) {
            $docPath = $this->getParameter("document_dir").$document->getDocumentSource();
            // on supprime du dossier
            if(file_exists($docPath)){
                unlink($docPath);
            }
            $entityManager->remove($document);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_document_index', ['category_label' => $category_label], Response::HTTP_SEE_OTHER);
    }
}

templates/document/_delete_btn.html.twig
<form method="post" action="{{ path('app_document_delete', {'id': document.id, 'category_label': category_label}) }}" onsubmit="return confirm('Etes vous certain(e) de vouloir supprimer ce document ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ document.id) }}">
    <button class="btn" title="Supprimer">{{ source('@icons_path/delete.svg') }}</button>
</form>

templates/document/_form.html.twig
{{ form_start(form) }}
    <div class="mb-3">
        <label for="lastname">Nom du document</label>
        {{ form_widget(form.label) }}
    </div>
    {% if document.oldDocument != null %}
    <div class="mb-3">
        <iframe src="{{ asset('uploads/doc/' ~ document.oldDocument) }}" class="w-100"></iframe>
    </div>
    {% endif %}
    <div class="mb-3">
        <label for="firstname">Document (PDF)</label>
        {{ form_widget(form.documentSource) }}
        {{ form_errors(form.documentSource) }}
    </div>
    <div class="mb-3">
        {{ form_row(form.category) }}
    </div>
    {% include('components/_buttonSave.html.twig') %}
{{ form_end(form) }}

templates/document/edit.html.twig
{% extends 'admin/dashboard.html.twig' %}

{% block title %}New Document{% endblock %}

{% block content %}
<div class="row">
    <div class="col-lg-6 offset-lg-3">
    <h3>Modifier un document</h3>

    {{ form_start(form) }}
        <div class="mb-3">
            <label for="lastname">Nom du document</label>
            {{ form_widget(form.label) }}
        </div>
        {% if document.oldDocument != null %}
        <div class="mb-3">
            <iframe src="{{ asset('uploads/doc/' ~ document.oldDocument) }}" class="w-100"></iframe>
        </div>
        {% endif %}
        <div class="mb-3">
            <label for="firstname">Document (PDF)</label>
            {{ form_widget(form.documentSource) }}
            {{ form_errors(form.documentSource) }}
        </div>
        <div class="mb-3">
            {% if category_label != 'association' %}
            <label for="category">Pour quel accueil ?</label>
            {% endif %}
            {{ form_widget(form.category) }}
            {{ form_errors(form.category) }}
        </div>
        {% include('components/_buttonSave.html.twig') %}
    {{ form_end(form) }}
    </div>
</div>
{% endblock %}

templates/document/index.html.twig
{% extends 'admin/dashboard.html.twig' %}

{% block title %}Document index{% endblock %}

{% block breadcrumb %}
    {% if category_label == 'périscolaire' %}
    <li class="breadcrumb-item"><a href="{{ path('app_admin_periscolaire') }}" class="text-dark">Accueil périscolaire</a></li>
    <li class="breadcrumb-item">Documents {{ category_label }}</li>
    {% elseif category_label == 'mercredi' %}
    <li class="breadcrumb-item"><a href="{{ path('app_admin_mercredi') }}" class="text-dark">Accueil de loisirs du mercredi</a></li>
    <li class="breadcrumb-item">Documents {{ category_label }}</li>
    {% elseif category_label == 'loisirs' %}
    <li class="breadcrumb-item"><a href="{{ path('app_admin_loisirs') }}" class="text-dark">Accueil de loisirs</a></li>
    <li class="breadcrumb-item">Documents {{ category_label }}</li>
    {% elseif category_label == 'infos' %}
    <li class="breadcrumb-item"><a href="{{ path('app_admin_informations') }}" class="text-dark">Infos pratiques</a></li>
    <li class="breadcrumb-item">Tous les documents</li>
    {% elseif category_label == 'association' %}
    <li class="breadcrumb-item"><a href="{{ path('app_admin_association') }}" class="text-dark">Association</a></li>
    <li class="breadcrumb-item">Documents de l'association</li>
    {% endif %}
{% endblock %}

{% block content %}
    {% if category_label == 'infos' %}
    <h3>Tous les documents à télécharger</h3>
    {% elseif category_label == 'association' %}
    <h3>Documents de l'association</h3>
    {% else %}
    <h3>Documents pour l'accueil {{ category_label }}</h3>
    {% endif %}
    <a href="{{ path('app_document_new', {'category_label': category_label}) }}" class="btn text-primary">
        {{ source('@icons_path/plus.svg') }} Créer
    </a>
    <table class="table">
        <thead>
            <tr>
                <th>Nom du document</th>
                <th>Categorie</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for document in documents %}
            <tr>
                <td>
                    <a href="{{ path('app_document_show', {'id': document.id}) }}" class="text-dark">
                        {{ document.label }}
                    </a>
                </td>
                <td>
                    <a href="{{ path('app_document_show', {'id': document.id}) }}" class="text-dark">
                        <ul>
                        {% for category in document.category %}
                            <li>{{ category.label }}</li>
                        {% endfor %}
                        </ul>
                    </a>
                </td>
                <td class="col-1">
                    <div class="row">
                        <div class="col-6">
                            <a href="{{ path('app_document_edit', {'id': document.id, 'category_label': category_label}) }}" title="Modifier" class="btn">
                                {{ source('@icons_path/update.svg') }}
                            </a>
                        </div>
                        <div class="col-6">
                            {{ include('document/_delete_btn.html.twig') }}
                        </div>
                    </div>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">Aucune donnée</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/document/new.html.twig
{% extends 'admin/dashboard.html.twig' %}

{% block title %}New Document{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{{ path('app_admin_informations') }}" class="text-dark">Infos pratiques</a></li>
    <li class="breadcrumb-item"><a href="{{ path('app_document_index', {'category_label': category_label}) }}" class="text-dark">Documents</a></li>
    <li class="breadcrumb-item">Créer</li>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-lg-6 offset-lg-3">
    <h3>Créer un nouveau document</h3>

    {{ form_start(form) }}
        <div class="mb-3">
            <label for="lastname">Nom du document</label>
            {{ form_widget(form.label) }}
        </div>
        {% if document.oldDocument != null %}
        <div class="mb-3">
            <iframe src="{{ asset('uploads/doc/' ~ document.oldDocument) }}" class="w-100"></iframe>
        </div>
        {% endif %}
        <div class="mb-3">
            <label for="firstname">Document (PDF)</label>
            {{ form_widget(form.documentSource) }}
            {{ form_errors(form.documentSource) }}
        </div>
        <div class="mb-3">
            {% if category_label != 'association' %}
            <label for="category">Pour quel accueil ?</label>
            {% endif %}
            {{ form_widget(form.category) }}
            {{ form_errors(form.category) }}
        </div>
        {% include('components/_buttonSave.html.twig') %}
    {{ form_end(form) }}
    </div>
</div>
{% endblock %}

templates/document/show.html.twig
{% extends 'admin/dashboard.html.twig' %}

{% block title %}Document{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{{ path('app_admin_informations') }}" class="text-dark">Infos pratiques</a></li>
    <li class="breadcrumb-item"><a href="{{ path('app_document_index') }}" class="text-dark">Documents</a></li>
    <li class="breadcrumb-item">{{ document.label }}</li>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-lg-6 offset-lg-3">
        <h3>Document</h3>

        <table class="table">
            <tbody>
                <tr>
                    <th>Nom du document</th>
                    <td>{{ document.label }}</td>
                </tr>
                <tr class="col-8">
                    <th>Document</th>
                    <td><iframe src="{{ asset('uploads/doc/' ~ document.documentSource) }}" class="w-100"></iframe></td>
                </tr>
                <tr class="col-8">
                    <th>Accueil</th>
                    <td>
                    {% for category in document.category %}
                        <li>{{ category.label }}</li>
                    {% endfor %}
                    </td>
                </tr>
                <tr>
                    <th>Modifier</th>
                    <td>
                        <a href="{{ path('app_document_edit', {'id': document.id}) }}" title="Modifier" class="btn">
                            {{ source('@icons_path/update.svg') }}
                        </a>
                    </td>
                </tr>
                <tr>
                    <th>Supprimer</th>
                    <td>{{ include('document/_delete_btn.html.twig') }}</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
{% endblock %}